name: first_app
description: A new flutter application project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  application:
    androidPackage: com.example.firstapp
    iosBundleIdentifier: com.example.firstApp
  assets:
    - assets/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/Oswald-Bold.ttf
          weight: 700